### ISSUE TITLE
Build Components

### ISSUE THREAD

**Issue by matkoch** [lukaspieper/dotnet-build-system#11]
Hey Lukas,

hast du lust einen teil der infrastruktur hier als components zu implementieren? Aehnlich wie hier fuers package signing oder global tool installation:

https://github.com/nuke-build/nuke/tree/develop/source/Nuke.Components

Beachte, beide sind als interfaces implementiert, und koennen daher im baukastenprinzip benutzt werden.

**Comment by lukaspieper** [comment]
Hi Matthias,

ich freue mich wirklich sehr über deine Anfrage. Wie bist du auf mein kleines Projekt aufmerksam geworden?

Gerne implementiere ich Teile meines Buildsystems in Nuke, allerdings bin ich mir unsicher für welche Teile du dich interessierst?

**Comment by matkoch** [comment]
Ich such regelmaessig ueber die github suche wer `using Nuke.Common` in seinem projekt hat :)

Grundsaetzlich interessier ich mich fuer alle teile... code analyse, packaging, compilation... alles was man so standardmaessig braucht. die interface default members wurden extra dafuer gebaut. falls es dich interessiert, koennte man mal nen meeting dazu machen.

**Comment by lukaspieper** [comment]
Bin interessiert und gerade dem Nuke-Slack beigetreten, alles weitere dann gerne darüber.
